#pragma once

//GAME SETTINGS
#define GAME_SPEED 3;
#define ALLOWED_BRICKS 2;
#define BOARDH 20
#define BOARDW 10

//CONSOLE SETTINGS
#define FONTSIZE 18

#define TETRIS_PIECE_SYMBOL (char)219
#define SNAKE_PIECE_SYMBOL (char)177
#define BOARD_EDGE_SYMBOL (char)176//(char)219
#define FOOD_SYMBOL 'O'

#define WINDOWH 30
#define WINDOWW 40


//DO NOT EDIT THIS
#define MENU_NEXT 1
#define MENU_PREV 0

#define DIRECTION_RIGHT 0
#define DIRECTION_DOWN 1
#define DIRECTION_LEFT 2
#define DIRECTION_UP 3
#define ACTION_1 4
#define ACTION_2 5

#define COLOR_BLACK 0
#define COLOR_BLUE 1
#define COLOR_GREEN 2
#define COLOR_CYAN 3
#define COLOR_RED 4
#define COLOR_PINK 5
#define COLOR_YELLOW 6
#define COLOR_WHITE 7
#define COLOR_GRAY 8
#define COLOR_LIGHTBLUE 9
#define COLOR_LIGHTGREEN 10
#define COLOR_LIGHTCYAN 11
#define COLOR_LIGHTRED 12
#define COLOR_LIGHTPINK 13
#define COLOR_LIGHTYELLOW 14
#define COLOR_LIGHTWHITE 15